#1885: Update API documentation endpoints
mojaloop/central-ledger pull request #798
Opened 2020-12-09 14:33 UTC by oderayi

2020-12-09 14:56 UTC, elnyry-sam-k submitted a review, later dismissed

2020-12-10 10:26 UTC, mdebarros requested changes
See my comment.

2020-12-10 10:26 UTC, mdebarros commented on config/default.json
> +  "API_DOCUMENTATION_ENDPOINTS": true,
Please add a `_ENABLED` prefix, perhaps something like this:
`API_DOCUMENTATION_ENDPOINTS` --> `API_DOC_ENDPOINTS_ENABLED`

2020-12-11 09:39 UTC, elnyry-sam-k approved these changes

2020-12-11 09:47 UTC, vijayg10 approved these changes

2020-12-11 12:43 UTC, vijayg10 approved these changes

2020-12-11 13:45 UTC, merged