Fix/#1945 cgs
mojaloop/central-ledger pull request #811
Opened 2021-01-22 14:10 UTC by vgenev

fix: settlementModel has currency as required
BREAKING CHANGE: currency is mandatory on /post settlementModels
creation of settlementModel on startup has been removed

2021-01-22 15:42 UTC, mdebarros requested changes
It looks good! Some minor comments for you to address.

Also, please add an additional comment to the POST /settlementModels API that it will create any associated ledgerAccountTypes for every participant that matches the settlementModel's currency

2021-01-22 15:42 UTC, mdebarros commented on src/api/ledgerAccountTypes/handler.js
>  // TODO: Below code is commented since there is no requirement to create ledgerAccountType using API.
Shouldn't this comment be removed?

2021-01-22 15:42 UTC, mdebarros commented on src/api/settlementModels/routes.js
> +          ledgerAccountType: Joi.string().required().description('Account type for the settlement model POSITION, SETTLEMENT or INTERCHANGE_FEE'),
The description needs to be updated.

`Account type for the settlement model POSITION, SETTLEMENT or INTERCHANGE_FEE` -> `Account type for the settlement model`

2021-01-22 15:42 UTC, mdebarros commented on src/domain/settlement/index.js
> +    await ParticipantService.validateHubAccounts(settlementModel.currency)
Please add a comment indicating why this is put here.

2021-01-22 15:42 UTC, mdebarros commented on test/integration/helpers/settlementModels.js
> +// exports.deletePreparedData = async (participantName) => {
Do we need this?

If so, please add a comment as to why its here.

2021-01-22 16:29 UTC, mdebarros requested changes
See minor comment.

2021-01-22 16:29 UTC, mdebarros commented on src/domain/settlement/index.js
> +    // check for existing hub account with the settlementModel currency
But why? :D

2021-01-22 16:29 UTC, vgenev commented on src/domain/settlement/index.js
> +    // check for existing hub account with the settlementModel currency
:D

2021-01-25 08:47 UTC, mdebarros approved these changes

2021-02-02 13:44 UTC, mdebarros approved these changes
+1

2021-02-02 13:51 UTC, merged

2021-02-03 05:25 UTC, lewisdaly commented
Nice title!